-- ============================================================
-- Migration: Social system tables
-- user_follows, item_interests, user_brotherhoods,
-- auto_brotherhoods, brotherhood_members, brotherhood_invitations
-- Execute in Supabase SQL Editor
-- ============================================================

-- ── user_follows ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_follows (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  following_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at   timestamptz DEFAULT now(),
  UNIQUE(follower_id, following_id),
  CHECK (follower_id != following_id)
);

CREATE INDEX IF NOT EXISTS idx_user_follows_follower  ON user_follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_following ON user_follows(following_id);

ALTER TABLE user_follows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read user_follows"  ON user_follows FOR SELECT USING (true);
CREATE POLICY "Users follow others"       ON user_follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "Users unfollow"            ON user_follows FOR DELETE USING (auth.uid() = follower_id);

-- ── item_interests ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS item_interests (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_id    text NOT NULL,
  item_type  text NOT NULL CHECK (item_type IN ('wine', 'winery', 'experience', 'region', 'grape', 'brotherhood')),
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_item_interests_user_id ON item_interests(user_id);
CREATE INDEX IF NOT EXISTS idx_item_interests_item_id ON item_interests(item_id);

ALTER TABLE item_interests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read all interests"     ON item_interests FOR SELECT USING (true);
CREATE POLICY "Users add own interests"      ON item_interests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users remove own interests"   ON item_interests FOR DELETE USING (auth.uid() = user_id);

-- ── user_brotherhoods (user-created groups) ──────────────────
CREATE TABLE IF NOT EXISTS user_brotherhoods (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text NOT NULL,
  description  text NOT NULL DEFAULT '',
  photo        text,
  creator_id   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  is_private   boolean DEFAULT false,
  member_count integer NOT NULL DEFAULT 1,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_brotherhoods_creator ON user_brotherhoods(creator_id);

ALTER TABLE user_brotherhoods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read public user_brotherhoods"   ON user_brotherhoods FOR SELECT USING (NOT is_private OR creator_id = auth.uid());
CREATE POLICY "Users create brotherhoods"       ON user_brotherhoods FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Creators update brotherhoods"    ON user_brotherhoods FOR UPDATE USING (auth.uid() = creator_id);
CREATE POLICY "Creators delete brotherhoods"    ON user_brotherhoods FOR DELETE USING (auth.uid() = creator_id);

-- ── auto_brotherhoods (auto-generated by item interest) ──────
CREATE TABLE IF NOT EXISTS auto_brotherhoods (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id      text NOT NULL UNIQUE,
  item_type    text NOT NULL CHECK (item_type IN ('wine', 'winery', 'experience', 'region', 'grape', 'brotherhood')),
  item_name    text NOT NULL,
  item_photo   text,
  member_count integer NOT NULL DEFAULT 0,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auto_brotherhoods_item_id ON auto_brotherhoods(item_id);

ALTER TABLE auto_brotherhoods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read auto_brotherhoods" ON auto_brotherhoods FOR SELECT USING (true);

-- ── brotherhood_members ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS brotherhood_members (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brotherhood_id    uuid NOT NULL,
  brotherhood_type  text NOT NULL CHECK (brotherhood_type IN ('user', 'auto')),
  user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role              text NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  joined_at         timestamptz DEFAULT now(),
  UNIQUE(brotherhood_id, brotherhood_type, user_id)
);

CREATE INDEX IF NOT EXISTS idx_brotherhood_members_bh    ON brotherhood_members(brotherhood_id, brotherhood_type);
CREATE INDEX IF NOT EXISTS idx_brotherhood_members_user  ON brotherhood_members(user_id);

ALTER TABLE brotherhood_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read brotherhood_members"  ON brotherhood_members FOR SELECT USING (true);
CREATE POLICY "Users join brotherhoods"          ON brotherhood_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users leave brotherhoods"         ON brotherhood_members FOR DELETE USING (auth.uid() = user_id);

-- ── brotherhood_invitations ──────────────────────────────────
CREATE TABLE IF NOT EXISTS brotherhood_invitations (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brotherhood_id uuid NOT NULL REFERENCES user_brotherhoods(id) ON DELETE CASCADE,
  inviter_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  invitee_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invitations_invitee ON brotherhood_invitations(invitee_id);
CREATE INDEX IF NOT EXISTS idx_invitations_status  ON brotherhood_invitations(status);

ALTER TABLE brotherhood_invitations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own invitations"   ON brotherhood_invitations FOR SELECT USING (auth.uid() = invitee_id OR auth.uid() = inviter_id);
CREATE POLICY "Members send invitations"     ON brotherhood_invitations FOR INSERT WITH CHECK (auth.uid() = inviter_id);
CREATE POLICY "Invitees respond"             ON brotherhood_invitations FOR UPDATE USING (auth.uid() = invitee_id);

-- ── triggers ─────────────────────────────────────────────────
CREATE TRIGGER update_user_brotherhoods_updated_at
  BEFORE UPDATE ON user_brotherhoods
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_auto_brotherhoods_updated_at
  BEFORE UPDATE ON auto_brotherhoods
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_brotherhood_invitations_updated_at
  BEFORE UPDATE ON brotherhood_invitations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
